[package]
name = "chess-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
raylib = "5.0.2"
viktoe-chess = { git = "https://github.com/INDA24PlusPlus/viktoe-chess" }
chess-networking = { git = "https://github.com/INDA24PlusPlus/chess-networking" }
rmp-serde = "1.3.0"
